// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJe5WJvS03EaQfWPOgOc2laHs5oUvxMII',
    appId: '1:918019570254:web:b0a3ee7c53a342ff2ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    authDomain: 'ecommerceapp-79423.firebaseapp.com',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    measurementId: 'G-GF99DKWS3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05XaP5E12DTG452DBubj99Ks6fDl-A8Q',
    appId: '1:918019570254:android:43b870901c83c0ac2ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0WeafrJmIO4Kx2YakRTJUenRwc_6e690',
    appId: '1:918019570254:ios:2120d9b7a5ba89622ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    androidClientId: '918019570254-g7eu5vlj9vfpa2sq3ciolq5239677q20.apps.googleusercontent.com',
    iosClientId: '918019570254-97fb9emniap4jg6uo4h9cm8lmiddhq2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0WeafrJmIO4Kx2YakRTJUenRwc_6e690',
    appId: '1:918019570254:ios:2120d9b7a5ba89622ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    androidClientId: '918019570254-g7eu5vlj9vfpa2sq3ciolq5239677q20.apps.googleusercontent.com',
    iosClientId: '918019570254-97fb9emniap4jg6uo4h9cm8lmiddhq2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJe5WJvS03EaQfWPOgOc2laHs5oUvxMII',
    appId: '1:918019570254:web:c54b5a561d22a5b42ca11f',
    messagingSenderId: '918019570254',
    projectId: 'ecommerceapp-79423',
    authDomain: 'ecommerceapp-79423.firebaseapp.com',
    storageBucket: 'ecommerceapp-79423.firebasestorage.app',
    measurementId: 'G-K8G40C3W0H',
  );

}